# Permalinks
permalink:           pretty

# Setup
title:               पदभञ्जिका
tagline:             attempts at focus via writing
url:                 https://rrp.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ramapriyan Pratiwadi
  url:               https://rrp.github.io
  email:             rpratiwadi@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/rrp/rrp.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
